import type { Metadata } from "next";
import "./globals.css";
import { AppKit } from "./context/appkit";
import { Navigation } from "./components/header";
import { Footer } from "./components/footer";

export const metadata: Metadata = {
  title: "TBHF Test app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <AppKit>
          <Navigation />
          <div className="h-screen pb-12">{children}</div>
          <Footer />
        </AppKit>
      </body>
    </html>
  );
}
